# This workflow is for testing the Qualcomm Preflight Checks reusable workflow. 
# See https://github.com/qcom-actions for details on how to use it in your repository.

name: QC Preflight Checks

on:
  pull_request:
  push:
    branches: [main]

jobs:
  preflight:
    name: Run QC Preflight Checks
    uses: ./.github/workflows/reusable-qcom-preflight-checks-orchestrator.yml
    with:
      enable-semgrep-scan: true
      enable-dependency-review: true
      enable-repolinter-check: true
      enable-copyright-license-check: true
      enable-commit-email-check: true
      enable-commit-msg-check: false # change to true to see some commit message check failures
      commit-msg-check-extra-options: '{"check-blank-line": false}'
      enable-armor-checkers: true

    permissions:
      contents: read
      security-events: write
